import { CalendarIcon } from '@sanity/icons';
import { defineType, defineField } from 'sanity';

export default defineType({
  name: 'booking',
  title: 'Bookings',
  type: 'document',
  icon: CalendarIcon,
  groups: [
    { name: 'guest', title: '1. Guest Info', default: true },
    { name: 'dates', title: '2. Dates & Room' },
    { name: 'pricing', title: '3. Pricing' },
    { name: 'payment', title: '4. Payment' },
    { name: 'additional', title: '5. Additional Info' },
  ],
  fields: [
    defineField({
      name: 'bookingReference',
      title: 'Booking Reference',
      type: 'string',
      validation: (Rule) => Rule.required(),
      description: 'Unique booking reference (auto-generated or enter manually for walk-ins)',
      initialValue: () => `MHL-${Date.now().toString().slice(-8)}`,
      group: 'guest',
    }),
    defineField({
      name: 'guestName',
      title: 'Guest Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'guest',
    }),
    defineField({
      name: 'guestEmail',
      title: 'Guest Email',
      type: 'string',
      validation: (Rule) => Rule.required().email(),
      group: 'guest',
    }),
    defineField({
      name: 'guestPhone',
      title: 'Guest Phone',
      type: 'string',
      validation: (Rule) => Rule.required(),
      group: 'guest',
    }),
    defineField({
      name: 'nationality',
      title: 'Guest Nationality',
      type: 'string',
      description: 'Guest country (for visa receipts)',
      group: 'guest',
    }),
    defineField({
      name: 'passportNumber',
      title: 'Passport Number',
      type: 'string',
      description: 'Optional: For international guests requiring visa documentation',
      group: 'guest',
    }),
    defineField({
      name: 'ghanaCardNumber',
      title: 'Ghana Card Number',
      type: 'string',
      description: 'Optional: For Ghanaian guests - Ghana Card identification number',
      group: 'guest',
    }),
    defineField({
      name: 'room',
      title: 'Room',
      type: 'reference',
      to: [{ type: 'roomSimplified' }],
      validation: (Rule) => Rule.required(),
      group: 'dates',
    }),
    defineField({
      name: 'checkIn',
      title: 'Check-in Date',
      type: 'date',
      validation: (Rule) => Rule.required(),
      group: 'dates',
    }),
    defineField({
      name: 'checkOut',
      title: 'Check-out Date',
      type: 'date',
      validation: (Rule) => Rule.required(),
      group: 'dates',
    }),
    defineField({
      name: 'numberOfRooms',
      title: 'Number of Rooms',
      type: 'number',
      description: 'Number of separate rooms booked in this reservation',
      validation: (Rule) => Rule.required().min(1).integer(),
      initialValue: 1,
      group: 'dates',
    }),
    defineField({
      name: 'adults',
      title: 'Number of Adults',
      type: 'number',
      validation: (Rule) => Rule.required().min(1),
      initialValue: 1,
      group: 'dates',
    }),
    defineField({
      name: 'children',
      title: 'Number of Children',
      type: 'number',
      initialValue: 0,
      validation: (Rule) => Rule.min(0),
      group: 'dates',
    }),
    defineField({
      name: 'roomPricePerNight',
      title: 'Room Price Per Night (GH₵)',
      type: 'number',
      description: 'The nightly rate for this booking (stored for receipt generation)',
      validation: (Rule) => Rule.min(0),
      group: 'pricing',
    }),
    defineField({
      name: 'totalPrice',
      title: 'Total Price (GH₵)',
      type: 'number',
      validation: (Rule) => Rule.required().min(0),
      group: 'pricing',
    }),
    defineField({
      name: 'status',
      title: 'Booking Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending', value: 'pending' },
          { title: 'Confirmed', value: 'confirmed' },
          { title: 'Cancelled', value: 'cancelled' },
          { title: 'Completed', value: 'completed' },
        ],
      },
      initialValue: 'pending',
      validation: (Rule) => Rule.required(),
      group: 'pricing',
    }),
    defineField({
      name: 'paymentStatus',
      title: 'Payment Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending', value: 'pending' },
          { title: 'Partial Payment', value: 'partial' },
          { title: 'Paid in Full', value: 'paid' },
          { title: 'Refunded', value: 'refunded' },
        ],
      },
      initialValue: 'pending',
      group: 'payment',
    }),
    defineField({
      name: 'amountPaid',
      title: 'Amount Paid (GH₵)',
      type: 'number',
      description: 'Amount already paid (for partial payments or deposits)',
      validation: (Rule) => Rule.min(0),
      group: 'payment',
    }),
    defineField({
      name: 'paymentMethod',
      title: 'Payment Method',
      type: 'string',
      options: {
        list: [
          { title: 'Telecel Cash (Mobile Money)', value: 'telecel' },
          { title: 'MTN Mobile Money', value: 'mtn' },
          { title: 'Vodafone Cash', value: 'vodafone' },
          { title: 'Bank Transfer', value: 'bank_transfer' },
          { title: 'Cash', value: 'cash' },
          { title: 'Credit/Debit Card', value: 'card' },
          { title: 'Other', value: 'other' },
        ],
      },
      description: 'How the guest paid or will pay',
      group: 'payment',
    }),
    defineField({
      name: 'paymentReference',
      title: 'Payment Reference/Transaction ID',
      type: 'string',
      description: 'Mobile money transaction ID, bank reference, etc.',
      group: 'payment',
    }),
    defineField({
      name: 'paymentNotes',
      title: 'Payment Notes',
      type: 'text',
      rows: 3,
      description: 'Additional payment details or instructions',
      group: 'payment',
    }),
    defineField({
      name: 'paymentIntentId',
      title: 'Stripe Payment Intent ID',
      type: 'string',
      hidden: true,
      group: 'payment',
    }),
    defineField({
      name: 'specialRequests',
      title: 'Special Requests',
      type: 'text',
      rows: 3,
      group: 'additional',
    }),
    defineField({
      name: 'receiptNumber',
      title: 'Receipt Number',
      type: 'string',
      description: 'Unique receipt identifier for accounting (optional)',
      group: 'additional',
    }),
    defineField({
      name: 'receiptIssued',
      title: 'Receipt Issued',
      type: 'boolean',
      initialValue: false,
      description: 'Whether a formal receipt has been generated',
      group: 'additional',
    }),
    defineField({
      name: 'receiptIssuedAt',
      title: 'Receipt Issued Date',
      type: 'datetime',
      description: 'When the receipt was first generated',
      group: 'additional',
    }),
    defineField({
      name: 'createdAt',
      title: 'Created At',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      group: 'additional',
    }),
    defineField({
      name: 'confirmationSent',
      title: 'Confirmation Email Sent',
      type: 'boolean',
      initialValue: false,
      group: 'additional',
    }),
    defineField({
      name: 'reminderSent',
      title: 'Reminder Email Sent',
      type: 'boolean',
      initialValue: false,
      group: 'additional',
    }),
    defineField({
      name: 'checkInFormData',
      title: 'Check-In Form Data',
      type: 'object',
      description: 'Additional information from pre-check-in form',
      group: 'additional',
      fields: [
        { name: 'dateOfBirth', title: 'Date of Birth', type: 'date' },
        { name: 'roomPreference', title: 'Room Preference', type: 'string' },
        { name: 'arrivalTime', title: 'Arrival Time', type: 'string' },
        { name: 'needsPickup', title: 'Needs Pickup', type: 'boolean' },
        { name: 'emergencyContactName', title: 'Emergency Contact Name', type: 'string' },
        { name: 'emergencyContactPhone', title: 'Emergency Contact Phone', type: 'string' },
        { name: 'emergencyContactRelation', title: 'Emergency Contact Relation', type: 'string' },
        { name: 'submittedAt', title: 'Submitted At', type: 'datetime' },
      ],
    }),
  ],
  preview: {
    select: {
      guestName: 'guestName',
      room: 'room.title',
      checkIn: 'checkIn',
      status: 'status',
      reference: 'bookingReference',
    },
    prepare({ guestName, room, checkIn, status, reference }) {
      return {
        title: `${reference} - ${guestName}`,
        subtitle: `${room} • Check-in: ${checkIn} • ${status}`,
      };
    },
  },
  orderings: [
    {
      title: 'Check-in Date',
      name: 'checkInDate',
      by: [{ field: 'checkIn', direction: 'desc' }],
    },
    {
      title: 'Created Date',
      name: 'createdDate',
      by: [{ field: 'createdAt', direction: 'desc' }],
    },
  ],
});
